version: '3'

services:

  python:
    restart: always
    build: .
    command: gunicorn --bind 0.0.0.0:8000 outletavto.wsgi:application
    volumes:
      - static_volume:/srv/www/outletavto/static/
    expose:
      - 8000
    ports:
      - 8000:8000

  nginx:
    restart: always
    image: nginx:latest
    build: ./nginx
    expose:
      - 8080
    ports:
      - "80:8080"
    depends_on:
      - python
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/srv/www/outletavto/static/
  volumes:
    static_volume