version: '3'

services:

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 outletavto.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d