# Generated by Django 4.1.7 on 2023-07-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FizUser',
        ),
        migrations.DeleteModel(
            name='UrUser',
        ),
    ]
