# Generated by Django 4.1.7 on 2023-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
