# Generated by Django 4.1.7 on 2023-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_fizuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizuser',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='uruser',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
