# Generated by Django 4.1.7 on 2023-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fizuser_is_active_uruser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uruser',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
