# Generated by Django 4.1.7 on 2023-07-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
        migrations.DeleteModel(
            name='FizUser',
        ),
        migrations.DeleteModel(
            name='UrUser',
        ),
    ]
