name: outletavto
on:
  push:
    branches:
      - main

jobs:
  deploy:
#    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Execute shell commands
        run: |
          cd /data/outletavto
          git pull
          git submodule update --remote
          docker image prune --force
          docker system prune --all --volumes
          docker-compose down --volumes --remove-orphans
          docker-compose up --build -d
